### ISSUE TITLE
API KEY flicker

### ISSUE THREAD

**Issue by bangiqi** [sgzsh269/android-mvp-architecture#3]
where to use API_KEY Const variable? i search it in RemoteDataSource class, variable is never used? how to?

**Comment by sgzsh269** [comment]
@ramdanisource the API_KEY is added to all requests using the OkHttp Interceptor as defined [here](https://github.com/sgzsh269/android-mvp-architecture/blob/master/app/src/prod/java/com/sagarnileshshah/carouselmvp/di/Injection.java#L45) in the `Injection` class for `prod` flavour. 
The reason there are 2 flavors `prod` and `mock` with `Injection` class is to help inject a [FakeRemoteDataSource](https://github.com/sgzsh269/android-mvp-architecture/blob/master/app/src/mock/java/com/sagarnileshshah/carouselmvp/di/Injection.java#L16) into `DataRepository` to return certain mock data or simulate a network situation for testing.

**Comment by sgzsh269** [comment]
Closing this issue, let me know if you have any further queries
