### ISSUE TITLE
Duplicate class found "Injection"

### ISSUE THREAD

**Issue by TheReprator** [sgzsh269/android-mvp-architecture#4]
When i run the code, i got the following error

Duplicate class found in the file '/home/local/M/vikram.singh/Downloads/android-mvp-architecture-master/app/src/mock/java/com/sagarnileshshah/carouselmvp/di/Injection.java

Duplicate class found in the file '/home/local/M/vikram.singh/Downloads/android-mvp-architecture-master/app/src/mock/java/com/sagarnileshshah/carouselmvp/di/Injection.java

 with Android Studio Canary 3.O canary 4, declare flavoured dimension, i am attaching a screenshot
![screenshot from 2017-06-23 02 20 47](https://user-images.githubusercontent.com/10286587/27455412-cee4471e-57ba-11e7-86bb-c6b01d7696df.png)

Please sort this issue as i am a newbie in architectural pattern.

**Comment by Visualrainy** [comment]
@TheGreat0004 does this issue resolved? I experience same issue as you posted
