### ISSUE TITLE
Build Error: Missing configuration file

### ISSUE THREAD

**Issue by ghost** [sgzsh269/android-mvp-architecture#5]
A configuration file is missing. Build fails. Screenshots attached
![mvp-fail1](https://user-images.githubusercontent.com/12413782/29932720-bd53052c-8e7d-11e7-93b2-a0522f7017c1.png)
![mvp-fail2](https://user-images.githubusercontent.com/12413782/29932719-bccf0466-8e7d-11e7-888e-6087efccca99.png)

**Comment by sgzsh269** [comment]
@muhindi5 I have added the `project.properties` file template to the root level, it basically just contains one field `flickrApiKey` which you have to initialize with your own Flickr API key.

Closing this ticket for now, let me know if you face any more issues.

**Comment by ghost** [comment]
Thanks alot, will update you incase of any more issues.
